default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  <<: *default
  host: localhost
  database: lemoney_development

test:
  <<: *default
  host: localhost
  database: lemoney_test

production:
  <<: *default
  database: lemoney_production
  url: <%= ENV['DATABASE_URL'] %>
